name: Povod CI Tests

# Триггеры: Когда запускать этот workflow
on:
  push:
    branches:
      - main      # Запускать при пуше в ветку main
      - develop   # Запускать при пуше в ветку develop
  pull_request:
    branches:
      - main      # Запускать при создании/обновлении Pull Request в ветку main

# Задачи (jobs), которые будут выполняться
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mongodb:

        image: mongo:latest 
        ports:
          - 27017:27017

    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4 # Используем готовый Action

      # Шаг 2: Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # Включить кеширование npm-пакетов для ускорения

      # Шаг 3: Установка зависимостей проекта
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Запуск тестов Cypress
      - name: Run Cypress tests
        run: npm run test:ci
        env:
          MONGODB_URI: mongodb://localhost:27017/povod-test-db
          PORT: 3001
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: cypress/
          retention-days: 30