name: Povod CI Tests and Reports

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  zap_baseline_scan:
    runs-on: ubuntu-latest
     name: ZAP Baseline Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js (for DAST target app)
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies (for DAST target app)
        run: npm ci
      - name: Start application for ZAP Scan
        run: npm run start:ci &
        env:
          MONGODB_URI: mongodb://localhost:27017/povod_test
          PORT: 3002
          SESSION_SECRET: 'dast_secret_key'
      - name: Wait for application to start
        run: |
          sleep 30 # Даем приложению время на запуск
          curl -I http://localhost:3002/healthz # Проверяем healthz

      # Запускаем ZAP Baseline Scan
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0 # Используем официальный ZAP action
        with:
          # target: 'https://your-staging-app-url.com' # Если сканируем внешний URL
          target: 'http://localhost:3002' # Сканируем приложение, запущенное в этом job
          rules_file_name: '.zap/rules.tsv' # Опционально: файл с правилами для игнорирования
          cmd_options: '-a' # Включить альфа-правила (более новые, могут быть нестабильны)
          # docker_name: 'owasp/zap2docker-stable' # Можно указать Docker image ZAP

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always() # Загружать отчет всегда
        with:
          name: zap-baseline-report
          path: zaproxy-report.html # Имя файла отчета по умолчанию для action-baseline

  test-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pages: write    
      id-token: write

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (SAST)
        run: npm run lint

      - name: Run Jest unit tests (generates Allure results)
        run: npm run test:unit

      - name: Run Cypress tests (generates Allure results)
        run: npm run test:ci 
        env:
          MONGODB_URI: mongodb://localhost:27017/povod_ci_test
          PORT: 3001
          SESSION_SECRET: ${{ secrets.SESSION_SECRET || 'a_very_strong_ci_secret_key_default' }} 
          # CYPRESS_BASE_URL: http://localhost:3001

      - name: Store Cypress artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-failures
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7

      - name: Set up Allure Commandline
        run: npm install -g allure-commandline

      - name: Create Allure Environment Properties
        if: always()
        run: |
          echo "Application_Version=$(npm pkg get version | tr -d '\"')" > allure-results/environment.properties
          echo "Base_URL=${{ env.CYPRESS_BASE_URL || 'http://localhost:3001' }}" >> allure-results/environment.properties
          echo "Node.js_Version=$(node -v)" >> allure-results/environment.properties 
          echo "Operating_System=${{ runner.os }}" >> allure-results/environment.properties
          echo "Branch=${{ github.ref_name }}" >> allure-results/environment.properties
          echo "Commit_SHA=${{ github.sha }}" >> allure-results/environment.properties
          echo "Run_ID=${{ github.run_id }}" >> allure-results/environment.properties
          echo "Triggered_By=${{ github.actor }}" >> allure-results/environment.properties

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-html-report
          path: allure-report
          retention-days: 30
          
      - name: Deploy Allure Report to GitHub Pages
        if: success() && (github.ref == 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@github.com'
          commit_message: 'Allure report'
          keep_files: true